#!/usr/bin/env python3
"""PreToolUse backstop — refuse auto-created skills the author has not blessed.

Quarantine is the primary control: the review fork writes to a scratch tree and
nothing reaches the live library until approved, so in normal operation this
hook has nothing to do. It exists for the paths quarantine does not cover -- a
skill approved once and later edited by hand, an entry restored from git, a
future code path that writes directly.

Five states, per skill:

    always   -- allow, never ask again (a person approved it)
    auto     -- ask once per session (the policy approved it; nobody read it)
    never    -- deny, never ask again
    session  -- allow for this session only (keyed on the hook's session_id)
    unset    -- ask the user

``auto`` is why this hook stopped being a formality. Under autonomous mode the
queue no longer stands between a proposal and the library, so this is the only
point where a person sees an auto-written skill before it does anything -- and
it fires at the moment the skill is about to act, for the small subset of
written skills that anything actually tries to use.

Skills without ``metadata.autoManaged: true`` are none of our business and are
always allowed: the user wrote them.

Registered as::

    "PreToolUse": [{"matcher": "Skill", "hooks": [
        {"type": "command", "command": "python3 .../skillgate.py"}]}]
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict

sys.path.insert(0, str(Path(__file__).resolve().parent))

import guard  # noqa: E402
import pending  # noqa: E402

SESSION_KEY = "sessions"


def respond(decision: str, reason: str = "") -> None:
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": decision,
            "permissionDecisionReason": reason,
        }
    }))


def session_verdict(session_id: str, skill: str) -> str | None:
    data = pending.read_approvals()
    return (data.get(SESSION_KEY, {}).get(session_id, {}) or {}).get(skill)


def set_session_verdict(session_id: str, skill: str, verdict: str) -> None:
    data = pending.read_approvals()
    data.setdefault(SESSION_KEY, {}).setdefault(session_id, {})[skill] = verdict
    pending.write_approvals(data)


def skill_metadata(skill: str) -> Dict[str, Any]:
    path = guard.SKILLS_DIR / skill / "SKILL.md"
    if not path.exists():
        return {}
    try:
        return guard.parse_frontmatter(path.read_text(encoding="utf-8"))
    except OSError:
        return {}


def decide(payload: Dict[str, Any]) -> tuple[str, str]:
    skill = str((payload.get("tool_input") or {}).get("skill") or "")
    if not skill:
        return "allow", ""

    # Plugin skills arrive as "plugin:name" and never live in SKILLS_DIR.
    frontmatter = skill_metadata(skill.split(":")[-1])
    if not frontmatter or not guard.is_auto_managed(frontmatter):
        return "allow", ""

    name = skill.split(":")[-1]
    verdict = pending.approval_for(name)
    if verdict == "always":
        return "allow", ""
    if verdict == "never":
        return "deny", (
            f"'{name}' was auto-generated by patina, the self-improvement loop, and you "
            f"previously declined it. To change that: "
            f"pending.py approve {name}"
        )

    session_id = str(payload.get("session_id") or "")
    if session_id:
        scoped = session_verdict(session_id, name)
        if scoped == "always":
            return "allow", ""
        if scoped == "never":
            return "deny", f"'{name}' was declined for this session."

    created_from = str(
        (frontmatter.get("metadata") or {}).get("createdFrom", "unknown")
    )
    if verdict == "auto":
        return "ask", (
            f"'{name}' was written AND approved automatically by patina, the "
            f"self-improvement loop (from session {created_from[:8]}). It passed "
            f"the policy, but no person has read it. This is the first time "
            f"anything has tried to use it.\n"
            f"Inspect it first with:  cat {guard.SKILLS_DIR / name / 'SKILL.md'}\n"
            f"Decide permanently:     patina pending approve {name}  |  "
            f"patina pending reject {name}"
        )
    return "ask", (
        f"'{name}' was written automatically by patina, the self-improvement loop, "
        f"(from session {created_from[:8]}), not by you. Approve using it?\n"
        f"Inspect it first with:  cat {guard.SKILLS_DIR / name / 'SKILL.md'}\n"
        f"Decide permanently:     patina pending approve {name}  |  "
        f"patina pending reject {name}"
    )


def main() -> int:
    try:
        payload = json.loads(sys.stdin.read() or "{}")
    except (json.JSONDecodeError, OSError):
        respond("allow")
        return 0
    try:
        decision, reason = decide(payload)
    except Exception:  # noqa: BLE001 — never block a session on a gate bug
        respond("allow")
        return 0
    respond(decision, reason)
    return 0


if __name__ == "__main__":
    sys.exit(main())
